### ISSUE TITLE
Don't require monolog

### ISSUE THREAD

**Issue by DanielRuf** [femtopixel/monolog-csvhandler#3]
https://github.com/femtopixel/monolog-csvhandler/blob/master/composer.json#L21

This breaks projects if we require this in a Symfony monolog bundle (Symfony 4) which uses Monolog 1.25.3.

**Comment by DanielRuf** [comment]
It should be a "peer" dependency and not require its own version of monolog.

**Comment by jaymoulin** [comment]
Thank you for reporting this. If you find this product useful, please consider donation to help me continue maintain and create great products ([![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin))

The version of `monolog-csvhandler` you try to use alongside Symfony 4 is not designed to work with it as it require monolog 2.0. 
If you want to use this with a deprecated version of Symfony and Monolog, I suggest you `composer require femtopixel/monolog-csvhandle "^0.1.2"` (hence, the major version number update)

**Comment by DanielRuf** [comment]
Yes I saw that. But should it really require monolog again? At least you pin the versions so this could cause conflicts.
